### ISSUE TITLE
COMMUNICATE with client to get her opinions on the Family and Applicant forms

### ISSUE THREAD

**Issue by robjansen15** [robjansen15/IHCApp#25]

**Comment by jagodfrey** [comment]
In regards to the family and student application forms, Lauren had this to say:
"Hi Jim,

I think it's pretty intuitive, although there are a couple of things that may need to be reworded (let me think about them).  One of the lines on the application is also repeated twice.  Thanks for finding a format that can also be used on a mobile device.  I can't believe I hadn't thought of that the first time we met!

I hope the presentation on Wednesday went well.  I was disappointed that it overlapped the IUPUI International Festival."

Waiting on one more reply from her about details and then I will close the issue.
Edit: Going to try and plan a phone call with Lauren for Wednesday/next monday depending on availability
